### ISSUE TITLE
Audit UI code

### ISSUE THREAD

**Issue by wei2912** [AY2122S1-CS2103-W14-2/tp#205]
The following classes relevant to UI functionality should be audited:

- [ ] `CommandBox`
- [ ] `HelpWindow`
- [ ] `MainWindow`
- [ ] `PersonCard`
- [ ] `PersonListPanel`
- [ ] `ResultDisplay`
- [ ] `StatusBarFooter`
- [ ] `Ui`
- [ ] `UiManager`
- [ ] `UiPart`

**Comment by jennibearduit** [comment]
Code looks fine, the constructor for `PersonCard` seems a little long, but I don't think that's a problem. 

May want to consider adding a `getNumFailedCalls` method to `Person` to avoid violation of LoD. Currently I see `person.getCallStatus().getNumFailedCalls()` being used everywhere.
