### ISSUE TITLE
`track2gather_32.png` is outdated

### ISSUE THREAD

**Issue by wei2912** [AY2122S1-CS2103-W14-2/tp#208]
This issue will make more sense after my refactor comes out.

**Comment by wei2912** [comment]
See https://github.com/AY2122S1-CS2103-W14-2/tp/blob/master/src/main/resources/images/track2gather_32.png. Should be 32px version of the bigger icon, I think.

**Comment by frederickpek** [comment]
What I did was to use the `track2gather_icon.png` for the logo, just resized. Perhaps I can remove this file in a future PR.
