### ISSUE TITLE
Error message for `CaseNumber` does not explain that case number must be at most 6 digits

### ISSUE THREAD

**Issue by wei2912** [AY2122S1-CS2103-W14-2/tp#98]
The current error message for `CaseNumber` states that "Case number should be a positive integer with no leading zeros", but does not explain that the case number should be at most 6 digits, as the validation regex enforces:

```java
public static final String VALIDATION_REGEX = "^[1-9]\\d{0,5}$";
```

**Comment by jennibearduit** [comment]
This issue has been fixed.
